# Generated by Django 5.1.7 on 2025-09-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trafficapp', '0006_trafficrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficrule',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='rules_files/'),
        ),
    ]
