# Generated by Django 5.1.7 on 2025-09-05 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trafficapp', '0007_trafficrule_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficrule',
            name='description',
        ),
    ]
