# Generated by Django 5.1.7 on 2025-10-26 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trafficapp', '0011_remove_quizquestion_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Trafficapp.quiztest'),
            preserve_default=False,
        ),
    ]
