# Generated by Django 5.1.7 on 2025-10-26 10:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trafficapp', '0012_alter_quizquestion_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_answer',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Trafficapp.quiztest'),
        ),
    ]
