# Generated by Django 5.1.7 on 2025-12-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trafficapp', '0015_quiztest_created_by_alter_quiztest_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficrule',
            name='title',
        ),
        migrations.AddField(
            model_name='trafficrule',
            name='title_en',
            field=models.CharField(default='Untitled', max_length=255, verbose_name='Title (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trafficrule',
            name='title_ur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (Urdu)'),
        ),
    ]
